name: mindeye
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py310h8a20257_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=1.1.1w=hd590300_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.0=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.8=h7a1cb2a_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h59595ed_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.23
      - albumentations==1.4.24
      - all-clip==1.3.0
      - aniso8601==10.0.1
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autofaiss==2.18.0
      - beartype==0.22.9
      - blinker==1.9.0
      - braceexpand==0.1.7
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip==0.2.0
      - clip-anytorch==2.6.0
      - clip-retrieval==2.45.0
      - cmake==4.2.1
      - coca-pytorch==0.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dalle2-pytorch==1.15.6
      - dataclasses==0.6
      - diffusers==0.13.0
      - einops==0.8.1
      - einx==0.3.0
      - ema-pytorch==0.7.9
      - embedding-reader==1.8.1
      - exifread-nocycle==3.0.1
      - faiss-cpu==1.13.2
      - filelock==3.20.1
      - fire==0.5.0
      - flask==3.1.2
      - flask-cors==4.0.2
      - flask-restful==0.3.10
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.25.2
      - idna==3.11
      - imageio==2.37.2
      - img2dataset==1.47.0
      - importlib-metadata==8.7.1
      - info-nce-pytorch==0.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lit==18.1.8
      - llvmlite==0.46.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - multilingual-clip==1.0.10
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - open-clip-torch==2.32.0
      - opencv-python-headless==4.11.0.86
      - pandas==2.3.3
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==15.0.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pynndescent==0.5.13
      - pyparsing==3.3.1
      - pytorch-msssim==1.0.0
      - pytorch-warmup==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - resize-right==0.0.2
      - rotary-embedding-torch==0.8.9
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scikit-metrics==0.1.0
      - scipy==1.15.3
      - sentence-transformers==2.7.0
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - simsimd==6.5.12
      - smmap==5.0.2
      - stringzilla==4.5.1
      - sympy==1.14.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tokenizers==0.21.4
      - torch==2.0.1
      - torch-fidelity==0.3.0
      - torchmetrics==1.8.2
      - torchvision==0.15.2
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==2.0.0
      - typer-slim==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - umap-learn==0.5.9.post2
      - urllib3==2.6.2
      - vector-quantize-pytorch==1.25.2
      - wandb==0.23.1
      - webdataset==0.2.111
      - werkzeug==3.1.4
      - x-clip==0.14.4
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /opt/conda/envs/mindeye
